services:
  api:
    image: ghcr.io/quack79/f1-dash-api:latest
    networks:
      - internal
    environment:
      - RUST_LOG=api=info
      - ADDRESS=0.0.0.0:80
      - ORIGIN=https://${F1_DOMAIN:-localhost}

  realtime:
    image: ghcr.io/quack79/f1-dash-realtime:latest
    ports:
      - 4000:80
    networks:
      - internal
    environment:
      - RUST_LOG=realtime=info
      - ADDRESS=0.0.0.0:80
      - ORIGIN=https://${F1_DOMAIN:-localhost}

  web:
    image: ghcr.io/quack79/f1-dash:latest
    depends_on:
      - realtime
      - api
    ports:
      - 3000:3000
    networks:
      - internal
    environment:
      - NEXT_PUBLIC_LIVE_URL=https://realtime.${F1_DOMAIN:-localhost}
      - API_URL=http://api

networks:
  internal:
    driver: bridge
