name: release

# runs on tag push and docker branch push

on:
  push:
    branches:
      - docker
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  build-dashboard:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER }}/f1-dash
          tags: |
            type=ref,event=branch,branch=docker,value=dev
            type=semver,pattern={{version}}

      - name: Build and push
        id: push
        uses: docker/bake-action@v6.6.0
        with:
          targets: f1-dash
          push: true
          provenance: true
          files: |
            cwd://${{ steps.meta.outputs.bake-file }}

  build-rust:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Extract Docker Metadata (api)
        id: meta-api
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER }}/f1-dash-api
          bake-target: f1-dash-api
          tags: |
            type=ref,event=branch,branch=docker,value=dev
            type=semver,pattern={{version}}

      - name: Extract Docker Metadata (realtime)
        id: meta-realtime
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER }}/f1-dash-realtime
          bake-target: f1-dash-realtime
          tags: |
            type=ref,event=branch,branch=docker,value=dev
            type=semver,pattern={{version}}

      - name: Build and push
        id: push
        uses: docker/bake-action@v6.6.0
        with:
          targets: f1-dash-api f1-dash-realtime
          push: true
          provenance: true
          files: |
            cwd://${{ steps.meta-api.outputs.bake-file }}
            cwd://${{ steps.meta-realtime.outputs.bake-file }}
